repos:
  - repo: local
    hooks:
      - id: black
        name: Black
        entry: black .
        language: system
        types: [python]

      - id: isort
        name: Isort
        entry: isort .
        language: system
        types: [python]

      - id: pylint
        name: Pylint
        entry: pylint src tests
        language: system
        types: [python]

      - id: pydocstyle
        name: Pydocstyle
        entry: pydocstyle src
        language: system
        types: [python]

      - id: run-pytest
        name: Run Pytest
        entry: pytest
        language: system
        types: [python]