repos:
  - repo: local
    hooks:
      - id: black
        name: Black
        entry: black
        args: [.]
        language: system
        types: [python]

      - id: isort
        name: Isort
        entry: isort
        args: [.]
        language: system
        types: [python]

      - id: pydocstyle
        name: Pydocstyle
        entry: pydocstyle
        args: [src]
        language: system
        types: [python]

      - id: run-pytest
        name: Run Pytest
        entry: pytest
        args: [tests]
        language: system
        types: [python]