name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar PDM
        run: pip install pdm

      - name: Instalar dependencias con PDM
        run: pdm install

      - name: Run flake8
        run: flake8 src tests

      - name: Run mypy
        run: mypy src

      - name: Correr los Tests
        run: pytest